name: EF Migrations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        working-directory: ./src/MoneyTale.Web

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef
      
    - name: Update database
      env:
        ASPNETCORE_ENVIRONMENT: CI
      run: dotnet ef database update